FROM nginx:alpine
# Copy all HTML/CSS files into the NGINX web root
COPY index.html /usr/share/nginx/html/
COPY privacy /usr/share/nginx/html/privacy/
COPY assets /usr/share/nginx/html/assets/

# Expose port 80
EXPOSE 80
